apiVersion: v1
kind: Service
metadata:
  name: portfoliotracker-service
  namespace: portfoliotracker
  labels:
    app: portfoliotracker
spec:
  selector:
    app: portfoliotracker
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP