apiVersion: v2
name: mathcorp-calculator
description: MathCorp's flagship calculator service Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@mathcorp.com