apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mathcorp-calculator.fullname" . }}
  labels:
    {{- include "mathcorp-calculator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mathcorp-calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mathcorp-calculator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: ENVIRONMENT
              value: {{ .Values.mathcorp.environment }}
            - name: LOG_LEVEL
              value: {{ .Values.mathcorp.logLevel }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}