replicaCount: 2

image:
  repository: mathcorp-calculator
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# MathCorp specific configurations
mathcorp:
  environment: development
  logLevel: info
  features:
    advancedMath: false
serviceAccount:
  create: true
  name: ""